### ISSUE TITLE
AttributeError: module 'building_footprint_segmentation.seg.binary.models' has no attribute 'A1BuNet'

### ISSUE THREAD

**Issue by santhi-2020** [fuzailpalnak/building-footprint-segmentation#24]
Hi,
Thank you in advance.
I am trying to use this code to segment the buildings. 
While loading the model we are getting the error like
"AttributeError: module 'building_footprint_segmentation.seg.binary.models' has no attribute "
Did I missed anything to install? your reply is more helpful for me.

**Comment by fuzailpalnak** [comment]
The lib doesn’t have the implementation for AlbuNet. It only has 3 network implemented  right now. Hence you are encountering Attribute error.

Is the AlbuNet you trying to run the same as mentioned in https://github.com/ternaus/robot-surgery-segmentation/blob/master/models.py


Regards
Fuzail

**Comment by santhi-2020** [comment]
Thank you Fuzailpalnak for your quick response, it is executed sucessfully. 
And one more question, is there any code for testing the model?
Do we have to write our own?

**Comment by fuzailpalnak** [comment]
If you wish to test locally then - https://github.com/fuzailpalnak/building-footprint-segmentation/issues/23#issuecomment-759915555, or you can test on deployed branch https://github.com/fuzailpalnak/building-footprint-segmentation/issues/23#issuecomment-759557274

Model weights used for test is uploaded at https://github.com/fuzailpalnak/building-footprint-segmentation/releases/download/alpha/refine.zip

**Comment by santhi-2020** [comment]
Thank you very much, the results are awesome. 
1.How to use original images parameters (w,h)  other than MAX_SIZE = 384? 
2.And also I can use GPU, if I change   map_location = gpu I am getting error
" state_dict = model_zoo.load_url(MODEL_URL, progress=True, map_location="cpu")"
can you suggest?

**Comment by fuzailpalnak** [comment]
- MAX_SIZE is just for convenience, you can set any dimension you wish, it just has to be multiple of 32.
- If you wish to run the network on GPU, then you don't need to change any variable, the code, `segmentation.load_model(name="ReFineNet")` parallelize the network if any GPUs are found. You just have to assign the extracted weights, which are on the CPU to the parallelized model.
        
    ```
    model =segmentation.load_model(name="ReFineNet")
    state_dict = model_zoo.load_url(MODEL_URL, progress=True, map_location="cpu")
    model.load_state_dict(state_dict)
    ```
**NOTE** - **The model should be initialized using the built-in library function rather than what's been done in https://github.com/fuzailpalnak/building-footprint-segmentation/issues/23#issuecomment-759915555**

**Comment by santhi-2020** [comment]
Understood Fuzail, Thank you..
If the input is gray how our model behaves?
![Capture](https://user-images.githubusercontent.com/72189453/118642362-e06dd980-b7f8-11eb-9826-01c5141b5e08.JPG)
![Capture2](https://user-images.githubusercontent.com/72189453/118642367-e2379d00-b7f8-11eb-99af-f4ebdc35e683.JPG)

**Comment by santhi-2020** [comment]
What are the steps we need to follow to detect building on these type of images?

**Comment by fuzailpalnak** [comment]
The model won't work for grayscale i.e **_1 band_** imagery as it was trained with RGB i.e **_3 bands_**.  You will have to train a separate model to achieve optimal results on grayscale imagery i.e **_1 band_**.
