### ISSUE TITLE
How to train the data with the given datasets(in the repository)?

### ISSUE THREAD

**Issue by santhi-2020** [fuzailpalnak/building-footprint-segmentation#25]
Hello Fuzail,

What are the inputs that I have to provide in the "data" folder to retrain the model.
Where can I get the label data.. could you please help me..
Thanks in advance and thank you for your support once again

Santhi

**Comment by fuzailpalnak** [comment]
- You can find examples to train [here](https://github.com/fuzailpalnak/building-footprint-segmentation/tree/main/examples).
- The format of the data folder : 


                    ├── train
                    │   ├── images          # images to train
                    │   ├── labels          # corresponding ground truth
                    |
                    ├── val
                    │   ├── images          # images to validate
                    │   ├── labels          # corresponding ground truth
                    │
                    ├── test
                    │   ├── images          # Test files

- Dataset to train could be found [here](https://github.com/fuzailpalnak/building-footprint-segmentation/tree/429495bbe9195b12f6e4706509400fe6a51429a2#dataset)

**Comment by santhi-2020** [comment]
Hi Fuzail,
 we kept the data in the specified format and in the labels folder we placed the target maps(.tiff files)
while start training we are getting the error like
![error](https://user-images.githubusercontent.com/72189453/118964036-b5b08c00-b984-11eb-9987-97fca2817983.JPG)

**Comment by fuzailpalnak** [comment]
What is your input image dimension?

**Comment by santhi-2020** [comment]
The same samples that are available in the above link suggested by you

**Comment by fuzailpalnak** [comment]
You will have to make sure that the image dimensions are multiple of 32, if they are not, then you will have to adjust the input images so that they satisfy the constraint

**Comment by santhi-2020** [comment]
The error is resoled, but another one. My doubt is the labels are like tiff images here, so how it read the data, where are the actual labels? could you please help me.
![Capture_1](https://user-images.githubusercontent.com/72189453/118967087-e6de8b80-b987-11eb-9acd-b159294de8e9.JPG)

**Comment by fuzailpalnak** [comment]
I suggest you follow few data preparation steps

1. Check the number of images and labels are equal
2. The associated label should have the same name as its corresponding training image i.e **`data/images/1.tiff`**  its equivalent label **`data/labels/1.tiff`**
3. The label is binary and not grayscale

These are a few that are commonly followed for binary segmentation.

**Comment by santhi-2020** [comment]
Okay , I have verified
The number of images and labels are equal - yes they are same
The associated label should have the same name as its corresponding training image i.e data/images/1.tiff its equivalent label data/labels/1.tiff (train 136 and its labels are 136 , val 5 and labels are 5) 
The label is binary and not grayscale for binary segmentation - it is not grayscale it is binary please check below
![Capture_2](https://user-images.githubusercontent.com/72189453/118969661-f27f8180-b98a-11eb-91c2-66b92d83d11d.JPG)

**Comment by fuzailpalnak** [comment]
i cannot verify by just looking at the images, see if the numpy values is just 0 or 255

**Comment by fuzailpalnak** [comment]
And also the dimension of the label should be HxW

**Comment by fuzailpalnak** [comment]
![bellingham24](https://user-images.githubusercontent.com/24665570/118975726-ec40d380-b991-11eb-9b94-498b9f3fa42a.png)
use uploaded as a reference for your label. **_[File extension doesn't matter]_**

**Comment by fuzailpalnak** [comment]
Its difficult for me to give a definite answer, on whether the model will give desired results or not, however,  in theory, if you have sufficient enough data the model should perform better in detecting the building footprint, if thats the only goal.

**Comment by santhi-2020** [comment]
Thank you Fazail...How you are creating the labeled data like that raster tiff from the vector layers..is there any code.. I have created building polygon layer..can you help me

**Comment by fuzailpalnak** [comment]
Refer https://github.com/fuzailpalnak/building-footprint-segmentation/issues/26#issuecomment-1025107040
