### ISSUE TITLE
How to get outline of the mask as polygon

### ISSUE THREAD

**Issue by santhi-2020** [fuzailpalnak/building-footprint-segmentation#26]
Hi Fuzail,

How are you. Hope you are doing good.
Can you help me how can I extract the polygons of the detected buildings.
Any help is appreciated.

Thanks in advance,
San

**Comment by fuzailpalnak** [comment]
[Raster to Vector](https://rasterio.readthedocs.io/en/latest/topics/features.html), This should get you started.

Regards,
Fuzail Palnak

**Comment by santhi-2020** [comment]
Thank you for your reply.
So our building foot prints can be converted as vector using above reference. I will try and let you know.

**Comment by santhi-2020** [comment]
![Capture32_pre](https://user-images.githubusercontent.com/72189453/151532505-7b02a245-4863-4050-9e57-4226ff851636.jpg)
outline of buildings to be extracted and convert them to vector layers

**Comment by santhi-2020** [comment]
Hi Fazile,

Can you help me and share your thoughts, I am expecting your support in this.

Thank you very much,
Santhi

**Comment by fuzailpalnak** [comment]
Refer the link that I shared above and this https://gis.stackexchange.com/questions/187877/how-to-polygonize-raster-to-shapely-polygons/187883, this should help you with your conversion.

**Comment by santhi-2020** [comment]
Thank you Fuzail.
It is working for me.
![Capture_pre_P](https://user-images.githubusercontent.com/72189453/151927014-7c5ef718-617c-4895-85e7-d238043f20ea.jpg)

Thank you

**Comment by fuzailpalnak** [comment]
You are more than welcome, I'm glad I was able to help.

Regards,
Fuzail
