### ISSUE TITLE
GeoTiff as output

### ISSUE THREAD

**Issue by gmommi** [fuzailpalnak/building-footprint-segmentation#36]
I used the pretrained model to extract buildings footprint on a custom image. What I get is a jpeg or tiff image, how can I georeference it? Is it possible to get a **geotiff** as output?
Thank you.

**Comment by fuzailpalnak** [comment]
If you have the original geo-referenced image then you can copy its projections as suggested [here](https://gis.stackexchange.com/a/108703)
