### ISSUE TITLE
import error with latest albumentation versions

### ISSUE THREAD

**Issue by Tclack88** [fuzailpalnak/building-footprint-segmentation#37]
Hello, I tried running [your example](https://github.com/fuzailpalnak/building-footprint-segmentation/blob/main/examples/Run%20with%20defined%20arguments.ipynb), but there's an error. The one I got to was

```
ImportError: cannot import name 'from_dict' from 'albumentations' (/usr/local/lib/python3.7/dist-packages/albumentations/core/__init__.py)
```

I suspect in one of the albumentations updates, the locations of some methods were shifted around. There may be other import errors, I haven't gotten past this one just yet, but you may be quicker at finding it as you're more familiar with your code

**Comment by fuzailpalnak** [comment]
Which version of `albumentations` did you use ? is it `0.5.0` ?

**Comment by Tclack88** [comment]
The latest 1.2.0

I just now looked at your requirements.txt. Excuse me for not looking at it earlier. I'll try those versions and check back (But it would be nice to work with the latest version)

**Comment by Tclack88** [comment]
That issue is taken care of now, it's

```
AttributeError: module 'building_footprint_segmentation.seg.binary.models' has no attribute 'AlBuNet'
```

Is that something you had locally?

There's certainly going to be other problems, eg.

```
.
.
loader = segmentation.load_loader(
    root_folder=r"D:\Cypherics\Library\building-footprint-segmentation\data",
.
.

callbacks = CallbackList([BinaryTestCallback(r"D:\Cypherics\lib_check\out_data")])

# Ouptut from all the callbacks caller will be stored at the path specified in log_dir
for caller in  ["TrainChkCallback", "TimeCallback", "TensorBoardCallback", "TrainStateCallback", "BinaryTestCallback"]:
    callbacks.append(load_callback(r"D:\Cypherics\lib_check\out_data", caller))
```

All these lines which specifically call on `D:\Cypherics`, which looks like some local user directory will probably cause an error trying to run

**Comment by fuzailpalnak** [comment]
Apologies, that totally my bad, had the model removed, you can choose from any of these available models `[ReFineNetLite, MFRN, ReFineNet]` and yes you will have to configure the path and remove the hard coded path

**Comment by fuzailpalnak** [comment]
Please refer the updated examples in branch [exmaples](https://github.com/fuzailpalnak/building-footprint-segmentation/tree/example-model-fix), you will mow just have to configure the path for dataset and log dir.

**Comment by Tclack88** [comment]
That makes sense. Thank you. Sorry for all the handholding, but I have further questions. I assume I need to download the training data, you listed the massachussets and inria data set, where do those get placed?

I imagine it would be in the `root_folder` of this line:
```
root_folder=r"D:\Cypherics\Library\building-footprint-segmentation\data",
```
But it seems like it should be split into training and validation data, unless pytorch just takes care of all that somehow

Also load callback, is this supposed to be some initially empty directory?

```
  callbacks.append(load_callback(r"D:\Cypherics\lib_check\out_data", caller))
  ```

**Comment by fuzailpalnak** [comment]
for data you will have to download and split the data the library does not handle data splits the library expects the data be present in the following format 
```├── train
│   ├── images          # images to train
│   ├── labels          # corresponding ground truth
|
├── val
│   ├── images          # images to validate
│   ├── labels          # corresponding ground truth
│
├── test
│   ├── images  ```

and for logging it could be any directory and if the path does not exists then the library creates one.
hope this helps

**Comment by Tclack88** [comment]
It helps a lot, thank you very much!
