### ISSUE TITLE
ERROR: torchvision 0.14.1 has requirement pillow!=8.3.*,>=5.3.0, but you'll have pillow 8.3.2 which is incompatible.

### ISSUE THREAD

**Issue by hieule88** [fuzailpalnak/building-footprint-segmentation#44]
which torchvision version did u use ?

**Comment by fuzailpalnak** [comment]
torch                                1.10.2
torchaudio                       0.10.2
torchvision                       0.11.3
Pillow                               8.4.0

**Comment by hieule88** [comment]
I installed all requirements but still got "ModuleNotFoundError: No module named 'cv2'". Which version of opencv should I install ?

**Comment by fuzailpalnak** [comment]
opencv-python == 4.5.5.62
opencv-python-headless == 4.4.0.44

**Comment by hieule88** [comment]
I got that error: "ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/home/hieule/anaconda3/envs/roof/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)" then I search google and it said because of opencv-python 4.5.5.62

**Comment by hieule88** [comment]
I got this error "ImportError: cannot import name '_registerMatType' from 'cv2.cv2' (/home/hieule/anaconda3/envs/roof/lib/python3.7/site-packages/cv2/cv2.cpython-37m-x86_64-linux-gnu.so)" then I search google and it said because of opencv-python-headless version
