### ISSUE TITLE
ttAugment installation error - conflict in numpy versions

### ISSUE THREAD

**Issue by kavin160100** [fuzailpalnak/building-footprint-segmentation#47]
Hi
When I try to install ttAugment. it throws an error "pip subprocess to install build dependencies did not run successfully". So I tried installing the libraries individually with the exact versions used in the notebook PredictionWithAugmentations.ipynb. there is a conflict in the versions for image-fragment 0.2.2 and opencv-python 4.5.5.62.  How to solve and install ttAugment? 
![Screenshot 2023-06-03 223802](https://github.com/fuzailpalnak/building-footprint-segmentation/assets/135452240/c8315abf-e116-4d84-bc1a-ea1096d2fd46)

**Comment by fuzailpalnak** [comment]
try this installation command `pip install git+https://github.com/fuzailpalnak/ttAugment.git@versionBump`

**Comment by kavin160100** [comment]
It worked thank you.
