### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by gmommi** [fuzailpalnak/building-footprint-segmentation#48]
Hi! I'm using the weights of the model you trained on Inria to retrain a model with other aereial images. Which layers of the RefineNet should I retrain?
Thank you!

**Comment by fuzailpalnak** [comment]
I would suggest to train the refine net modules while keeping the backbone weights fixed

**Comment by gmommi** [comment]
Thank you! I don't get why if I set these parameteres like following in refinenet.py:
- pre_trained_image_net = false
- top_layers_trainable = false
- param.requires_grad = false (for resnet layers)
and I set transfer_weights = 'path of the model weights' in training.py,
when I run training.py twice and I print model weights they appear to be different even if i'm using the same model. It looks like model weights are not considered in the training phase but they are randomly initialized.
Could you please tell me how to modify the scripts to use weights from your model to initialize both resnet and refinenet layers ?

**Comment by fuzailpalnak** [comment]
I am not sure how are you loading the weights, this is how I did and its gives same weights each time `model = segmentation.load_model(name="ReFineNet", transfer_weights=r"C:\Users\Fuzail.Palnak\Downloads\refine\refine.pth", pre_trained_image_net = False, top_layers_trainable = False)
`

The `pre_trained_image_net`, `top_layers_trainable ` are relevant when training from scratch,  as far as just training the refine module with a pre-trained weights is concern, for that there is no direct implementation in the library, what you will have to do is after you load the model using the library function, set the params that you don't want to train to `false`, here is an example.

```
segmentation = init_segmentation("binary")

model = segmentation.load_model(name="ReFineNet", transfer_weights=r"Downloads/refine/refine.pth", pre_trained_image_net = False, top_layers_trainable = False)

for param in model.parameters():
  print(param.data)

# This will set layers from 0 to 161 to trainable = false and will only consider layers above 161 during update 
for i, param in enumerate(model.parameters()):
    if i <= 161:
        param.requires_grad = False
        
......
.....
```
