### ISSUE TITLE
How to test the model?

### ISSUE THREAD

**Issue by teresalisanti** [fuzailpalnak/building-footprint-segmentation#50]
Hi, 
why do you test your model using data augmentation as in PredictionWithAugmentations.py?
How did you choose which manipulation to be used?
By combining these outputs (eg. crop and resize results), how do you get the final estimate on the tile? 
Thank you :)

**Comment by fuzailpalnak** [comment]
1. Test time augmentations are used during inference to improve accuracy of the prediction, you can follow this [example ](https://github.com/fuzailpalnak/building-footprint-segmentation/blob/main/examples/PredictionWithAugmentations.ipynb). 
 
2. Following the research in the field to find what kind of test time augmentations are used for similar data.
